### ISSUE TITLE
How to judge the accuracy of model

### ISSUE THREAD

**Issue by WuxuanChen** [ralgond/kdd2021#1]
Hello, recently I am trying to solve this anomaly detection problem in KDD2021 competition as my study project. However, I do not have the real anomaly position in the dataset provided by KDD competition. May I ask how do you calculate the accuracy of your model? Is the file 'labels.txt' the real location of anomalies? Thank you!

**Comment by ralgond** [comment]
Yes, the file 'labels.txt' is the real location of anomalies.

To judge the accuracy of model, you can run eval.py as following:

python eval.py output\main4.csv

**Comment by WuxuanChen** [comment]
Thanks for your reply!
